### ISSUE TITLE
Code is not selectable in editor

### ISSUE THREAD

**Issue by mydeveloperday** [OpenCppCoverage/OpenCppCoveragePlugin#13]
After the coverage has changed the background color of lines which are executed/not executed, its no longer possible to see the selection

You have to edit the file to remove the coloring in order to be able to select a line of code (and see the selection)

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for reporting this issue.
You can remove the coverage colors by unchecking ``Display Coverage ``
![displaycoverage](https://user-images.githubusercontent.com/19760133/37254732-4486174a-2542-11e8-869a-900d7ebe90e4.png)

``Display Coverage`` text is not visible with Visual Studio dark theme and so I need to change the background color.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage plugin [0.9.6.0](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.6.0) has a better support of the black theme.

I hope it will help,

OpenCppCoverage
