### ISSUE TITLE
Run CppCoverage context menu is too in your face!

### ISSUE THREAD

**Issue by mydeveloperday** [OpenCppCoverage/OpenCppCoveragePlugin#15]
Could you possibly consider moving the "Run OpenCppCoverage" button down to below clean,

Build
ReBuild
Clean

are things we use all day every day and are in our muscle memory,

The "Run OpenCppCoverage" button being in the middle is causing us to fire it when we didn't mean to!

![image](https://user-images.githubusercontent.com/16046346/37703881-0a7bd508-2cef-11e8-9437-1428585b1ac8.png)

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for the feedback. I will change the location in the next release!

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

It is fixed in [OpenCppCoverage 0.9.6.0](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.6.0).
Feel free to reopen this issue if you still have the problem.

OpenCppCoverage
