### ISSUE TITLE
Coverage and Settings panels should respect the color theme

### ISSUE THREAD

**Issue by jornb** [OpenCppCoverage/OpenCppCoveragePlugin#16]
It looks a bit strange with the dark theme now.

![image](https://user-images.githubusercontent.com/2614828/38482366-2e4aa13c-3bcf-11e8-9583-576444d8dacc.png)

**Comment by OpenCppCoverage** [comment]
Hello,

Indeed, the black theme looks a bit strange. There is also [this issue](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/issues/13).
I will try to see what I can do in the next release. 

OpenCppCoverage

**Comment by jornb** [comment]
Thanks. Loving the plugin, keep up the good work! :)

**Comment by OpenCppCoverage** [comment]
Hello,

It is fixed in [OpenCppCoverage 0.9.6.0 ](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.6.0).

OpenCppCoverage
