### ISSUE TITLE
Subsequent invocations of the plugin should remember previous settings

### ISSUE THREAD

**Issue by bert8128** [OpenCppCoverage/OpenCppCoveragePlugin#17]
If I have set some settings in the plugin dialog, then close the dialog and reopen, these settings have not been preserved (eg inclusions and exclusions).  It would be extremely useful to me if they were. Perhaps some people wouldn't like this, so optimally this would be controlled by a persisted tickbox on the dialog ("Preserve Settings", or some such).
Note that this should apply to separate invocations within the same visual studio session, and also after having closed and reopened visual studio.  This would be specific to a particular solution, like the debug settings.

**Comment by OpenCppCoverage** [comment]
Hello,

First, thank you for the feedback and sorry for my late answer!

When I wrote the first version of the plugin, I wanted to persist the settings in a file by project.
I did not because of a lack of time. I know this is an annoying problem in some cases.

I will release a new minor version (Do not know when) of the plugin with minor fixes. I will try to add this feature in this version too.
I will update this discussion when I have news to share.

OpenCppCoverage

**Comment by SweetLoverFT** [comment]
Dear developer,

Thanks for your contribute to provide such a fantastic tool for us, and I'd like to give the feedback from my experience with this tool in my solution. I found there's several things that I may care about:
1. Please display the default template settings when open this tool for a solution at the 1st time.
2. Keep the previous settings configured by users.
3. When projects' directories and the solution file aren't at the same directory, it will be better if this tool can display the default template.
4. For multiple projects, it will be better to save each of test settings.

Sincerely,
Miku.

**Comment by kgAtaka** [comment]
+1 :)

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) saves all settings by project. Please see [documentation](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/wiki).

@SweetLoverFT: Thank you very much for your feedback!
> 1. Please display the default template settings when open this tool for a solution at the 1st time.

This is the behavior now.

> 2. Keep the previous settings configured by users.

All settings are saved.

> 3. When projects' directories and the solution file aren't at the same directory, it will be better if this tool can display the default template.

Can you explain the use case?

> 4. For multiple projects, it will be better to save each of test settings.

Settings are saved by project.

> 5. May I editor in the working directory text box directly when it was checked?

I try to not make focus changes. As settings are now saved, it should be a smaller issue. Let me know if I misunderstood the problem.

> 6. Error: "--modules "..[path]\binary": Cannot contain "." (current folder) or ".." (parent folder).

`--module` is a filter on a full path so having `.` or `..` never match.

OpenCppCoverage.

**Comment by OpenCppCoverage** [comment]
Close this issue as [OpenCppCoverage Plugin 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.7.0) saves all settings by project.

OpenCppCoverage

**Comment by SweetLoverFT** [comment]
> Hello,
> 
> [OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) saves all settings by project. Please see [documentation](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/wiki).
> 
> @SweetLoverFT: Thank you very much for your feedback!
> 
> > 1. Please display the default template settings when open this tool for a solution at the 1st time.
> 
> This is the behavior now.
> 
> > 1. Keep the previous settings configured by users.
> 
> All settings are saved.
> 
> > 1. When projects' directories and the solution file aren't at the same directory, it will be better if this tool can display the default template.
> 
> Can you explain the use case?
> 
> > 1. For multiple projects, it will be better to save each of test settings.
> 
> Settings are saved by project.
> 
> > 1. May I editor in the working directory text box directly when it was checked?
> 
> I try to not make focus changes. As settings are now saved, it should be a smaller issue. Let me know if I misunderstood the problem.
> 
> > 1. Error: "--modules "..[path]\binary": Cannot contain "." (current folder) or ".." (parent folder).
> 
> `--module` is a filter on a full path so having `.` or `..` never match.
> 
> OpenCppCoverage.

Great
> Can you explain the use case?
For example, there're 5 projects in a visual studio solution, I need test them one by one:
As for the first one the filter is f1, the 2nd one is f2, none of them is the same, in this case if I open different project, it should different settings
