### ISSUE TITLE
How can I set excluded_line_regex?

### ISSUE THREAD

**Issue by joseAndresGomezTovar** [OpenCppCoverage/OpenCppCoveragePlugin#25]
There is some way to set the regular line expression option excluded
As the documentation says [https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference](url)
`
--excluded_line_regex arg: Exclude all lines match the regular expression. Regular expression must match the whole line.
`

**Comment by OpenCppCoverage** [comment]
Hello,

In ``Miscellaneous`` tab, you can set a config file. See [here](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--config_file-arg) for the syntax.

I hope it helps

OpenCppCoverage

**Comment by joseAndresGomezTovar** [comment]
It works fine
