### ISSUE TITLE
Settings-Filter not restore

### ISSUE THREAD

**Issue by seungyongshim** [OpenCppCoverage/OpenCppCoveragePlugin#27]
Visual Studio Professional 2017 15.9.6
OpenCppCoverage Plugin 0.9.6.1

First Running.
![image](https://user-images.githubusercontent.com/6711748/52764390-49d37080-3063-11e9-94c1-9a693b56dcec.png)

Second Running has to reset filter tap.
![image](https://user-images.githubusercontent.com/6711748/52764436-843d0d80-3063-11e9-82a1-dbc7098642f0.png)

How can I save filter options? It looks like bug, isn't it?

Regards

**Comment by OpenCppCoverage** [comment]
Hello,

This is the same as https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/issues/17.
It will be the next feature for OpenCppCoverage plugin. Please note I am also working on https://github.com/OpenCppCoverage and do not know when I will have time to implement it.

In the meantime, maybe https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/pull/22 can help you.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) saves all settings including filters. Please see [documentation](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/wiki) for further explanation. Feel free to reopen this issue or create a new one if the issue still persist for you.

OpenCppCoverage.
