### ISSUE TITLE
Make it available for Visual Studio 2019

### ISSUE THREAD

**Issue by michalfita** [OpenCppCoverage/OpenCppCoveragePlugin#29]
Visual Studio 2019 has been released, but OpenCppCoveragePlugin is not available in it's extension gallery yet.

Thank you.

**Comment by david-soane** [comment]
I've used it a little in Visual Studio 2019 and it seems to work. 

If you are just wanting to get it installed then you can just:
1. Download the vsix file
2. Open the OpenCppCoverage-0.9.6.1.vsix zip file
3. Modify the extension.vsixmanifest as per the instructions here:
https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/
4. Modify the catalog.json file -  modify the version for Microsoft.VisualStudio.Component.CoreEditor as per 3

**Comment by OpenCppCoverage** [comment]
Hello,

It is planned for the next release of the plugin.

OpenCppCoverage

**Comment by michalfita** [comment]
@OpenCppCoverage when is the next release planned?

**Comment by OpenCppCoverage** [comment]
Hello,

I am currently working on OpenCppCoverage release. When done, I will work on the plugin release.
The next release is planned in 1-3 months.

OpenCppCoverage

**Comment by lurumdare** [comment]
+1

**Comment by lurumdare** [comment]
@OpenCppCoverage How is it going?

**Comment by OpenCppCoverage** [comment]
Hello,

It is now available on master branch.

Here is an unofficial release: [VSPackage.zip](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/files/3348647/VSPackage.zip). Unzip the file and run ``VSPackage.vsix``.

OpenCppCoverage

**Comment by lurumdare** [comment]
@OpenCppCoverage https://youtu.be/d0mZQWABi3sd promote your extensions :D

**Comment by DieSlower** [comment]
Will there be a 0.9.8.0 version of the plugin available for VS2019?

**Comment by timkowd** [comment]
> Hello,
> 
> It is now available on master branch.
> 
> Here is an unofficial release: [VSPackage.zip](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/files/3348647/VSPackage.zip). Unzip the file and run `VSPackage.vsix`.
> 
> OpenCppCoverage

Hello, I was using this unofficial release, but it doesn't work since 16.3.7:

System.InvalidOperationException: Could not find the filters file in the project.
   at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , ComObject )
   at CallSite.Target(Closure , CallSite , Object )
   at OpenCppCoverage.VSPackage.DynamicVCConfiguration..ctor(Object configuration)

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) is available for Visual Studio 2019.

@DieSlower: It also includes OpenCppCoverage 0.9.8.0.

@timkowd: Can you retry with version 0.9.7.0 and open a new issue if the problem still occur? 

OpenCppCoverage

**Comment by timkowd** [comment]
Works fine, thanks !
