### ISSUE TITLE
Code coverage for ATL Projects (DLLs) 

### ISSUE THREAD

**Issue by cbigurra** [OpenCppCoverage/OpenCppCoveragePlugin#32]
Hello, 

I would like to use this plugin but I am having troubles executing the OpenCppCoveragePlugin. I have an ATL project and I would like to se the code coverage that my test cover form that project, so, is it possible to get the code coverage of an ATL project (.dll) with OpenCppCoveragePlugin? 

When I try to execute it, resturns the following:

![image](https://user-images.githubusercontent.com/5341093/72936683-4f364200-3d2d-11ea-9920-4531b635f8e4.png)

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoveragePlugin uses [OpenCppCoverage](https://github.com/OpenCppCoverage/OpenCppCoverage) that runs an executable. You cannot run directly a DLL and you should create an executable that call your ATL library. Let me know if you need some help (In this case, can you provide more detail about your ATL library?).

OpenCppCoverage

**Comment by cbigurra** [comment]
Hello,

Thank you for your answer. I already fixed it adding the executable ;)

**Comment by cbigurra** [comment]
And a last question, Does OpenCppCoverage support VSTest?

**Comment by cbigurra** [comment]
I found this flag: --cover_children. And it's seems that it is working well, but there is something weird: The Code Coverage results is always 100%, is that the expected behavior?

**Comment by cbigurra** [comment]
> The Code Coverage results is always 100%, is that the expected behavior?

Maybe this is another issue, but I'm not sure :P

**Comment by OpenCppCoverage** [comment]
Hello,

To run the plugin with `VSTest` see [How to run OpenCppCoverage with vstest.console.exe?](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#how-to-run-opencppcoverage-with-vstestconsoleexe)

> The Code Coverage results is always 100%, is that the expected behavior?

In `Miscellaneous` tab, select `verbose` mode and see [I cannot see my module in the code coverage report.](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#i-cannot-see-my-module-in-the-code-coverage-report.)

I hope it helps,

OpenCppCoverage
