### ISSUE TITLE
No full coverage

### ISSUE THREAD

**Issue by ThirtySomething** [OpenCppCoverage/OpenCppCoveragePlugin#5]
Hi @all,

I'm running OpenCppCoverage in Jenkins.  As test framework I'm using [Catch](https://github.com/philsquared/Catch). A simple string wrapper is completely covered by unit tests. Definitely all methods are called. But not all methods are marked as "covered" (green in HTML). Static methods for example. But there are also other methods I don't know the reason why they are not covered.

The scenario:
**OS:** Windows 7 Professional 64-Bit
**OpenCppCoverage:** 0.9.6.1
**Build environment:** Visual Studio 2017 Community Edition (full patched) / the msbuild of this Visual Studio used in Jenkins
**Build Type:** 32-/64-Bit Release

**Comment by ThirtySomething** [comment]
Uh, sorry, this issue occurs not using the plugin, but the OpenCppCoverage program on the shell. Can you please move it? Otherwise I'll recreate it.

**Comment by OpenCppCoverage** [comment]
Hello,

It looks like a compiler optimization issue.
The code coverage for a release build is not accurate for this reason.
Can you try testing with a debug build?

https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/issues/6 may be related to the same problem.

I hope it will help,

OpenCppCoverage

**Comment by ThirtySomething** [comment]
Hello,

thanks for the hint. Yes, your're right, a debug build will have a full coverage. So I'll close this issue.

Regards

Jochen
