### ISSUE TITLE
Get Error by creating

### ISSUE THREAD

**Issue by ManX070** [OpenCppCoverage/OpenCppCoveragePlugin#7]
VS 2017
installed 
-> OpenCppCoverageSetup-x64-0.9.6.1
-> OpenCppCoverageSetup-x86-0.9.6.1

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2547,5): warning MSB3283: Die Wrapperassembly für die Typbibliothek "Microsoft.VisualStudio.CommandBars" wurde nicht gefunden. Stellen Sie sicher, dass (1) die COM-Komponente richtig registriert ist und dass (2) die Zielplattform mit der Bitness der COM-Komponente übereinstimmt. Wenn die COM-Komponente z. B. 32-Bit ist, darf die Zielplattform nicht 64-Bit sein.

What  can i do to fix this bug

**Comment by OpenCppCoverage** [comment]
Hello,

It looks like you need Visual Studio 2017 version 15.3.X.
For more information: 
 - https://github.com/madskristensen/ShortcutExporter/issues/14 
 - https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/commit/27a9842d3dde6586cff5a5ccc60e6f018738395d

I hope it will help,

OpenCppCoverage
